[mypy]
# Общие настройки
follow_imports = silent
ignore_missing_imports = True

warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True

strict_optional = True

check_untyped_defs = True
disallow_untyped_defs = True
disallow_any_generics = True
disallow_any_expr = True
disallow_any_unimported = True
disallow_subclassing_any = True

# Исключения (директории и файлы, которые mypy должен игнорировать)
exclude = \.__pycache__\.
           |\.git
           |\.venv
           |alembic
           |docker
           |__init__\.py
