# Generated by Django 5.2.3 on 2025-06-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование института')),
                ('institute_num', models.IntegerField(unique=True, verbose_name='Порядковый номер института')),
            ],
            options={
                'verbose_name': 'Институт',
                'verbose_name_plural': 'Институты',
            },
        ),
        migrations.CreateModel(
            name='ReportsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField(verbose_name='Отчет в текстовом представлении')),
                ('report_json', models.JSONField(verbose_name='Отчёт в JSON формате')),
            ],
            options={
                'verbose_name': 'Архив отчётов',
            },
        ),
        migrations.CreateModel(
            name='StudentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=255)),
                ('course', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('student', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Архив студентов',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=5, unique=True, verbose_name='Наименование группы')),
                ('course', models.IntegerField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.institute')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=255, unique=True, verbose_name='Наименование группы')),
                ('leader', models.BooleanField(default=False, verbose_name='Староста группы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.group')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.institute')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
