# Generated by Django 5.2.3 on 2025-06-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='leader',
            new_name='is_leader',
        ),
        migrations.RenameField(
            model_name='institute',
            old_name='institute_num',
            new_name='institute_code',
        ),
    ]
