# Generated by Django 5.2.3 on 2025-06-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_rename_fields_into_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование группы'),
        ),
    ]
